services:
  - type: web
    name: doux-devis
    env: python
    pythonVersion: "3.11.0"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false
      - key: GIST_ID
        sync: false
      - key: GITHUB_TOKEN
        sync: false
